94 refactor work with exceptions
Palus-Somni-Team/shikicinema-server pull request #111
Opened 2023-05-28 16:56 UTC by BasicEC

В процессе работы над сервисом реквестов понял, что у нас нет нормального подхода к прокидыванию исключений.
Отсюда родился этот PR, прямого отношения к задаче не имеет.

Что было сделано и зачем? У нас был класс Assert который позволял делать проверку входных данных. Заходелось именть точно такую же штуку, но для проверки пользовательского ввода.
То есть, проверки у нас одинаковые, а вот ошибки мы хотим бросать иногда пользовательские (типо AlreadyExists), а иногда dev (типо разработчик передал в функцию null где нельзя).

2023-05-29 05:01 UTC, Smarthard requested changes
имхо: assertion'ы должны использоваться в функциях из utils или в чем-то вроде middlewares/interceptors/guards. Зачем их использовать в сервисах я не особо понимаю. Сервисы должны работать только с уже провалидированными значениями.

2023-05-29 15:47 UTC, BasicEC commented on projects/backend/src/utils/checks/dev/dev-assertion-validator.spec.ts
> +        expect(wasThrown).toBe(false);
Так смысл же в том что эта реализация ничего **не** делает при вызове `throwCollected`, разве тот код который ты написал не делает обратную проверку? (ну то есть проверяет что ошибка была брошена)

2023-05-29 15:48 UTC, BasicEC commented on projects/backend/src/utils/checks/user/user-assertion-validator.ts
> +    }
Этот валидатор не хранит состояние, а кидает исключения при добавлении, поэтому тут пустой метод

2023-05-29 15:53 UTC, BasicEC commented on projects/backend/src/services/author/author.service.ts
> +        DevAssert.Check('offset', offset).notNull().greaterOrEqualTo(0);
Есть 3 типа ошибок:
- Ошибка валидации - пользователь ввел херню. Эти ошибки отлавливает контроллер
- Ошибка бизнес логики - пользователь ввел корректные данные, но бизнес говорит, что само действие это фигня (пример: пользователь пытется создать видео которое уже есть). Такие ошибки должен обрабатывать сервис через `UserAssert`
- Ошибка программиста - программист написал фигню и вызывает метод с неправильными аргументами. (нет гарантий что сервис вызывается из контроллера и ввод валидны). Такие ошибки обрабатывает DevAssert и при их возникновении будет возвращен 500 код.

Обработкой дефолтных значений занимается контроллер. Поэтому этот код не противоречит issue которое ты кинул.

2023-05-29 15:54 UTC, BasicEC commented on projects/backend/src/services/author/author.service.ts
> +        DevAssert.Check('entityManager', entityManager).notNull();
описал выше в чем разница разных ассертов, закрываю. Давай в одном месте это обсуждать

2023-05-29 15:54 UTC, BasicEC commented on projects/backend/src/services/author/author.service.ts
> +        DevAssert.Check('author', author).notNull().lengthBetween(1, 256);
описал выше в чем разница разных ассертов, закрываю. Давай в одном месте это обсуждать

2023-05-29 15:57 UTC, BasicEC commented on projects/backend/src/services/author/author.service.ts
> +        const repo = await entityManager.getRepository(AuthorEntity);
`entityManager` приходит из транзакции. Поэтому этот код по идее должен выполняться в ней всегда.  По этой же причине repo получается из `.getRepository()` Я не уверен что иначе repo подхватит транзакцию и я не увидел способа передать транзакцию репозиторию для выполнения запросов.

2023-06-02 09:54 UTC, Smarthard commented on projects/backend/src/utils/checks/dev/dev-assert.ts
> +    public static Check<T>(name: string, value: T): Check<T> {
Почему Check с большой буквы?
и ещё надо чёт с неймингами придумать Dev/User assert придумать

2023-06-02 09:55 UTC, Smarthard commented on projects/backend/src/utils/checks/check.ts
> +    lengthBetween<TArray, TValue extends ArrayLike<TArray>>(
мне кажется эту проверку нужно распилить на `maxLength` и `minLength`

2023-06-02 10:01 UTC, Smarthard commented on projects/backend/src/utils/checks/check.ts
> +    notNull(this: Check<T>, message?: string): Check<T> {
`null` и `undefined` не одно и то же, `notFalsy` больше подходит

2023-06-02 10:07 UTC, Smarthard commented on projects/backend/src/utils/checks/dev/dev-assertion-validator.spec.ts
> +        expect(wasThrown).toBe(false);
ну тогда `.toReturn()`, но я всё ещё не понимаю смысл этого волшебного метода

2023-07-09 11:22 UTC, Smarthard commented on projects/backend/src/utils/checks/check.ts
> +    notNull(this: Check<T>, message?: string): Check<T> {
`notNullish`

2023-07-22 10:00 UTC, BasicEC commented on projects/backend/src/utils/checks/dev/dev-assertion-validator.spec.ts
> +        expect(wasThrown).toBe(false);
Тест умер. throwCollected удален

2023-07-22 10:01 UTC, BasicEC commented on projects/backend/src/utils/checks/user/user-assertion-validator.ts
> +    public static readonly instance = new UserAssertionValidator();
исправил

2023-07-22 10:01 UTC, BasicEC commented on projects/backend/src/utils/checks/dev/dev-assert.ts
> +    public static Check<T>(name: string, value: T): Check<T> {
check исправил, что не так с неймингами не очень понял.

2023-07-22 10:01 UTC, BasicEC commented on projects/backend/src/utils/checks/check.ts
> +    lengthBetween<TArray, TValue extends ArrayLike<TArray>>(
разделил

2023-07-22 10:01 UTC, BasicEC commented on projects/backend/src/utils/checks/check.ts
> +    notNull(this: Check<T>, message?: string): Check<T> {
исправил

2023-07-22 10:02 UTC, BasicEC commented on projects/backend/src/utils/checks/user/user-assertion-validator.ts
> +    }
Удалил throwCollected

2023-07-22 16:32 UTC, Smarthard approved these changes

2023-07-22 16:33 UTC, Smarthard commented on projects/backend/src/utils/checks/dev/dev-assert.ts
> +    public static Check<T>(name: string, value: T): Check<T> {
Я уже не помню, пусть пока такими будут

2023-07-22 16:33 UTC, merged