33 admin panel
Palus-Somni-Team/shikicinema-server pull request #115
Opened 2023-06-21 16:05 UTC by akdlsl

Создал проект админки + авторизация

2023-06-27 10:10 UTC, Smarthard requested changes
Пробежался по файлам, выписал моменты, которые надо обсудить или доработать. Если что накидывай свои идеи прям под комменты. Как соберемся - обсудим их

2023-06-27 10:10 UTC, Smarthard commented on projects/frontend/admin/src/assets/styles/variables.scss
> +  --bg-02: #f7fbff;
а в чем отличия?
эт разные градации одного цвета я так понимаю?

2023-06-27 10:10 UTC, Smarthard commented on projects/frontend/admin/src/index.html
> +<html lang="en">
у нас вроде ru без локализации, лучше поправить

2023-06-27 10:10 UTC, Smarthard commented on projects/frontend/admin/src/app/core/services/destroy.service.ts
он не используется и почему не `@ngneat/until-destroy` (его попроще использовать мне кажется)?

2023-06-28 14:25 UTC, akdlsl commented on projects/frontend/admin/src/assets/styles/variables.scss
> +  --bg-02: #f7fbff;
Пробуем настроить тему кастовую через материал @Smarthard

2023-07-06 10:03 UTC, BasicEC commented on projects/backend/src/main.ts
> +    const app = await NestFactory.create(AppModule, { cors: { credentials: true, origin: true} });
@Smarthard 
А у тебя разве нет балансировщика? Может настроим CORS там? А то настройка CORS на бэке, по моему опыту, заканчивается жуткой болью для разработки

2023-07-22 21:26 UTC, akdlsl commented on projects/frontend/admin/src/app/layout/components/header/header.component.scss
> +  h1 {
буэм, пока заюзал стили и компоненты материала

2023-07-22 21:27 UTC, akdlsl commented on projects/frontend/admin/src/app/auth/pages/auth-page/auth-page.component.html
> +  <button type="submit" class="btn" (click)="auth()">Войти</button>
Потом решим

2023-07-22 21:29 UTC, akdlsl commented on projects/backend/src/main.ts
> +    const app = await NestFactory.create(AppModule, { cors: { credentials: true, origin: true} });
Удалил

2023-07-23 11:28 UTC, Smarthard requested changes
Убрать зависимость лишнюю надо, а так гуд - сразу после мержим

2023-07-23 11:28 UTC, Smarthard commented on package.json
> +    "install": "^0.13.0"
Чет мне кажется это лишнее?

2023-07-23 17:59 UTC, Smarthard approved these changes

2023-07-23 18:00 UTC, merged