#6 User API
Palus-Somni-Team/shikicinema-server pull request #19
Opened 2020-08-27 11:57 UTC by Smarthard

2020-08-28 20:39 UTC, BasicEC requested changes

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/DeleteUserRequestValidator.ts
> +class PutUserRequestValidator extends Validator {
Мало проверок

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/DeleteUserRequestValidator.ts
> +class PutUserRequestValidator extends Validator {
Тут неправильное имя класса

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/PutUserRequestValidator.ts
> +    protected async validateCore(req: Request): Promise<void> {
мало проверок

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/DeleteUserRequestValidator.ts
> +class PutUserRequestValidator extends Validator {
Проверок тогда достаточно

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/router.ts
> +import {User as UserDTO} from '../../../lib/shikicinema';
Dto должны быть без суфикса DTO, а таблицы дожны оканчиваться на Entity

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/router.ts
> +    async (req, res, next) => {
тут у req не указан тип

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/router.ts
> +users.post(
Нужно сделать UserService.ts в котором будет методы Get, Create, Delete, Update

2020-08-28 20:39 UTC, BasicEC commented on src/routes/users/router.ts
> +    middleware.allowFor('user', 'admin'),
Что-то странное с этими мидлварями, надо разобраться где они нужны а где нет

2020-08-31 19:00 UTC, Smarthard commented on src/routes/users/DeleteUserRequestValidator.ts
> +class PutUserRequestValidator extends Validator {
Переименовано

2020-08-31 19:00 UTC, Smarthard commented on src/routes/users/PutUserRequestValidator.ts
> +    protected async validateCore(req: Request): Promise<void> {
Проверки добавлены

2020-08-31 19:01 UTC, Smarthard commented on src/routes/users/router.ts
> +import {User as UserDTO} from '../../../lib/shikicinema';
User -> UserEntity, UserDTO -> User from 'lib/shikicinema'

2020-08-31 19:03 UTC, Smarthard commented on src/routes/users/router.ts
> +    async (req, res, next) => {
Добавлены типы для всех endpoint'ов

2020-08-31 19:03 UTC, Smarthard commented on src/routes/users/router.ts
> +users.post(
Создан сервис UserRepo

2020-08-31 19:04 UTC, Smarthard commented on src/routes/users/router.ts
> +    middleware.allowFor('user', 'admin'),
Мидлвари убрал, т.к. они всё равно не будут нормально работать, пока не закроется issue #3.

2020-09-01 17:58 UTC, BasicEC requested changes

2020-09-01 17:58 UTC, BasicEC commented on lib/shikicinema/v2/GetByIdParamRequest.ts
> +}
Ощущение что переменные этого типа не обязательно содержат поле id

2020-09-01 17:58 UTC, BasicEC commented on lib/shikicinema/v2/users/GetUsersRequest.ts
> +}
Как-то скудно, нужно добавать суда фильтров (типо выбирать по роли и искать по email).
Можно оставить реализацию для отдельного issue

2020-09-01 17:58 UTC, BasicEC commented on lib/shikicinema/v2/users/Role.ts
> +export {Role} from '../../../../src/models/UserEntity';
Не, не, не. У нас не lib должна зависить от сервера, а сервер от lib

2020-09-01 17:58 UTC, BasicEC commented on lib/shikicinema/v2/users/UpdateUserRequest.ts
> +    shikimoriId?: number | null;
Зачем тут `| null`?

2020-09-01 17:58 UTC, BasicEC commented on lib/shikicinema/v2/users/User.ts
> +    shikimoriId: number | null;
Зачем тут `| null`?

2020-09-01 17:58 UTC, BasicEC commented on seeders/2020-08-27-01-scopes.js
> +'use strict';
я бы засунул `seeders` в каталог `migrations`, а то много каталогов в корне проекта. Это возможно?

2020-09-01 17:58 UTC, BasicEC commented on src/routes/users/CreateUsersRequestValidator.ts
> +            .withMessage('Login must be a string with length between 3 and 16 symbols')
Мы договаривались не писать имя поля в сообщении. Вместо этого использовать слово `value`. Имя поля есть в ошибке в отдельном поле.

2020-09-01 17:58 UTC, BasicEC commented on src/routes/users/GetUserByIdRequestValidator.ts
> +class GetUserByIdRequestValidator extends Validator {
Кажется таких валидаторов у нас будет дофига, думаю нужно вынести в `services` и назвать `GetByIdRequestValidator`, чтобы был один

2020-09-01 17:58 UTC, BasicEC commented on src/routes/users/GetUsersRequestValidator.ts
> +    protected async validateCore(req: QueryRequest<GetUsersRequest>): Promise<void> {
Нужно определиться с типом параметров,тут ты явно указываешь тип дто и используешь просто `Request` в Create, Get, Delete валидаторах.

2020-09-01 17:58 UTC, BasicEC commented on src/routes/users/PutUserRequestValidator.ts
> +                if (typeof roles[0] === 'string') {
Почему только первый элемент проверяется на то, является ли он строкой?
Вроде нужно бежать по всем и проверять:
- является ли строкой
- входит ли в список ролей

2020-09-01 17:58 UTC, BasicEC commented on src/routes/users/router.ts
> +        }
В моем представлении 2 два варианта
1. UserRepo - это репозиторий который управляет чисто запясими в бд и ничего не знает про dto. Соответственно ответственность за перевод entity в dto лежит на том кто использует UserRepo. И в разных местах программы могут быть разные dto.
2. UserRepo - это сервис который скрывает от всех остальной программы entity и вместо них отдает наружу dto. В этом случае у него есть метод toDTO (он private). И вся программа использует единообразные объекты.

Тут нужно либо вынести toDTO в контроллер и будет 1 вариант (что кажется хорошим решением)
Либо сделать toDTO private и не отдавать наружу entity. (тоже решение, но кажется, что потом могут вохникнуть проблемы, потому как то, что отдает UserRepo тоже вохможно придеться конвертить в другой объект)

Я голосую за первый вариант

2020-09-01 17:58 UTC, BasicEC commented on src/services/UserRepo.ts
> +}
Не понял... Если это Partial метод, то почему он вызывается у UserRepo в route.ts?

2020-09-01 17:58 UTC, BasicEC commented on src/services/UserRepo.ts
> +}
кажется такие Partial  методы лучше выносить в отдельные файлы

2020-09-01 17:58 UTC, BasicEC commented on src/services/UserRepo.ts
> +    async findById(id: number): Promise<UserEntity | null> {
Кажется что этот метод можно обобщить сразу на все модели. Как-то так:
```
async findById(model: Partial<T extends Model>): Promise<T | null> {
        try {
            return !isNaN(id) ? model.findByPk(id) : Promise.resolve(null);
        } catch (e) {
            return Promise.reject(e);
        }
    }
```

И вынести в отдельный файл

2020-09-01 17:58 UTC, BasicEC commented on src/types/Pagination.ts
> +export interface Pagination {
Думаю этот интерфейс должен быть в lib, оканчиваться на Request и от него должен кто-нибудь наследоваться

2020-09-01 18:00 UTC, Smarthard commented on lib/shikicinema/v2/GetByIdParamRequest.ts
> +}
Это воркэраунд, чтобы победить typescript.

2020-09-01 18:01 UTC, Smarthard commented on lib/shikicinema/v2/users/GetUsersRequest.ts
> +}
Можно добавить, но пока такой потребности нет, вроде.

2020-09-01 18:01 UTC, Smarthard commented on lib/shikicinema/v2/users/Role.ts
> +export {Role} from '../../../../src/models/UserEntity';
А вот это я зря, сыглы, поправлю.

2020-09-01 18:03 UTC, Smarthard commented on lib/shikicinema/v2/users/UpdateUserRequest.ts
> +    shikimoriId?: number | null;
Чтобы показать, что он nullable. В js `null` и `undefined` - разные штуки.

2020-09-01 18:03 UTC, Smarthard commented on lib/shikicinema/v2/users/User.ts
> +    shikimoriId: number | null;
Аналогично см. ответ выше.

2020-09-01 18:04 UTC, Smarthard commented on src/routes/users/PutUserRequestValidator.ts
> +                if (typeof roles[0] === 'string') {
Справедливо, поправлю.

2020-09-01 18:55 UTC, Smarthard commented on src/routes/users/router.ts
> +        }
Я тоже голосую за первый. И раз уж мы решили имплементить из lib/shikicinema нужные интерфейсы в классы toDTO можно сделать будет там.

2020-09-01 18:58 UTC, Smarthard commented on src/services/UserRepo.ts
> +}
`Partial` можно убрать, проверил.

2020-09-01 19:01 UTC, Smarthard commented on src/services/UserRepo.ts
> +    async findById(id: number): Promise<UserEntity | null> {
Можно, но не во всех моделях есть id  (например, в токенах) или он может быть строкой.

2020-09-02 14:55 UTC, Smarthard commented on src/types/Pagination.ts
> +export interface Pagination {
Перенес.

2020-09-02 14:56 UTC, Smarthard commented on src/services/UserRepo.ts
> +}
Убрал.

2020-09-02 14:56 UTC, Smarthard commented on src/routes/users/PutUserRequestValidator.ts
> +                if (typeof roles[0] === 'string') {
Исправил.

2020-09-02 14:57 UTC, Smarthard commented on lib/shikicinema/v2/users/Role.ts
> +export {Role} from '../../../../src/models/UserEntity';
Поправлено

2020-09-02 15:32 UTC, Smarthard commented on src/routes/users/router.ts
> +        }
Метод toDTO перенес в класс UserDTO в директории types/

2020-09-02 16:11 UTC, BasicEC commented on lib/shikicinema/v2/GetByIdParamRequest.ts
> +}
Тогда тут стоит оставить комментарий об этом

2020-09-02 16:17 UTC, BasicEC commented on src/services/UserRepo.ts
> +    async findById(id: number): Promise<UserEntity | null> {
резонно

2020-09-02 16:28 UTC, BasicEC requested changes

2020-09-02 16:28 UTC, BasicEC commented on lib/shikicinema/v2/users/GetUsersRequest.ts
> +export interface GetUsersRequest extends PaginationRequest, Partial<User> {}
непонял наследования от Partial<User>

2020-09-02 16:28 UTC, BasicEC commented on src/routes/users/GetUsersRequestValidator.ts
> +            .custom((roles) => UserEntity.isJSONRoles(roles))
Почему тут внезапно появился json? Почему roles это строка, а не массив и почему этот метод в Entity? Что произошло?

2020-09-03 09:15 UTC, Smarthard commented on lib/shikicinema/v2/users/GetUsersRequest.ts
> +export interface GetUsersRequest extends PaginationRequest, Partial<User> {}
Parial, чтобы можно было опускать поля, по которым нужна выборка из бд.

2020-09-03 12:32 UTC, Smarthard commented on lib/shikicinema/v2/GetByIdParamRequest.ts
> +}
Добавил комментарий.

2020-09-03 12:35 UTC, Smarthard commented on src/routes/users/GetUsersRequestValidator.ts
> +            .custom((roles) => UserEntity.isJSONRoles(roles))
Изменил тесты и вернул проверку на обычный массив строк. Сам метод переименовал в `isValidRoles` и перенес в `UserDTO`.

2020-09-06 14:57 UTC, Smarthard commented
Закрыто в связи с #27

2020-09-06 14:57 UTC, closed without merging