Set up eslint
Palus-Somni-Team/shikicinema-server pull request #57
Opened 2021-06-12 19:57 UTC by BasicEC

related #43

2021-06-25 15:34 UTC, Smarthard requested changes

2021-06-25 15:34 UTC, Smarthard commented on package.json
>      "eslint-config-prettier": "^7.0.0",
конфиг prettier для eslint надо удалить

2021-06-26 16:45 UTC, BasicEC commented on package.json
>      "eslint-config-prettier": "^7.0.0",
Выпилил

2021-06-27 22:07 UTC, Smarthard approved these changes

2021-06-30 19:34 UTC, Smarthard approved these changes

2021-06-30 19:34 UTC, merged