#25 Swagger documentation
Palus-Somni-Team/shikicinema-server pull request #77
Opened 2022-08-04 11:22 UTC by Smarthard

Resolves #25 

- Добавлен Swagger UI, который доступен на эндпоинте `/api/1.0`;
- Описаны параметры, query и DTO для всех актуальных эндпоинтов;
- Небольшие исправления для videos controller: там не использовалось приведение VideoEntity к VideoResponse, в то время как на админском роуте было именно так.

2022-08-27 15:01 UTC, BasicEC requested changes
Хотелось бы еще увидеть пару слов в README о том по какому пути доступен swagger

2022-08-27 15:30 UTC, Smarthard commented on src/routes/auth/dto/LoginRequest.dto.ts
> +    password: string;
Если я правильно помню, на авторизации у нас нет валидации

2022-08-27 16:01 UTC, Smarthard commented
> Хотелось бы еще увидеть пару слов в README о том по какому пути доступен swagger

Добавил в README секцию документации. Когда будет у нас на бою хоть что-то, можно будет ещё рабочую ссылку туда добавить.

2022-08-27 16:58 UTC, BasicEC commented on src/routes/auth/dto/LoginRequest.dto.ts
> +    password: string;
Ну запрос с пустыми полями не похож на валдиный. Можно вынести это в отдельное issue

2022-08-28 09:37 UTC, Smarthard commented on src/routes/auth/dto/LoginRequest.dto.ts
> +    password: string;
Вынес сюда: #81

2022-09-08 14:15 UTC, BasicEC approved these changes

2022-09-08 14:16 UTC, merged