45 test refactoring
Palus-Somni-Team/shikicinema-server pull request #80
Opened 2022-08-21 18:50 UTC by BasicEC

2022-08-22 09:54 UTC, Smarthard requested changes

2022-08-22 09:54 UTC, Smarthard commented on src/utils/http.utils.ts
> +export function queryString(obj: any): string {
У superagent есть парсер query из объекта:

https://visionmedia.github.io/superagent/#query-strings

2022-08-22 09:54 UTC, Smarthard commented on test/test.client.ts
> +        if (cookie?.length >= 0) {
возможно, стоит все куки забирать

2022-08-22 09:54 UTC, Smarthard commented on test/test.environment.ts
> +    protected App: INestApplication;
camelCase

2022-08-22 09:54 UTC, Smarthard commented on test/test.environment.ts
> +    get DataSource(): DataSource {
camelCase

2022-08-22 09:54 UTC, Smarthard commented on test/test.environment.ts
> +    get AnonClient(): TestClient {
camelCase

2022-08-22 09:54 UTC, Smarthard commented on test/test.environment.ts
> +    get ShikiAuthClient(): TestClient {
camelCase

2022-08-22 09:56 UTC, Smarthard commented on src/utils/http.utils.ts
> +export function queryString(obj: any): string {
обрати внимание перед тем, как это изменять
https://github.com/Palus-Somni-Team/shikicinema-server/pull/80#discussion_r951235669

2022-08-27 08:01 UTC, BasicEC commented on test/spec/videos.e2e.spec.ts
> +            };
она не такая же, там animeId, episode другие. Пока всего в двух местах используем, фиг с ним я думаю

2022-08-27 12:41 UTC, Smarthard approved these changes

2022-08-27 12:50 UTC, merged