WIP: 82 authors api
Palus-Somni-Team/shikicinema-server pull request #84
Opened 2022-10-15 13:25 UTC by BasicEC

2022-10-15 13:39 UTC, Smarthard commented on .vscode/settings.json
> +}
файлы IDE в проекте не нужны, добавь лучше `.vscode/` в .gitignore тогда

2022-10-15 13:42 UTC, BasicEC commented on .vscode/settings.json
> +}
Конкретно этот лучше оставить, .vscode/ уже есть в .gitignore, а этот файл там помечен как исключение

2022-10-16 21:26 UTC, Smarthard commented on migrations/2022-10-15-01-create-authors.xml
> +            </column>
В чём СМЫСОЛ?

2022-10-16 21:28 UTC, Smarthard commented on .vscode/settings.json
> +}
Опять же, в чем смысол хранить в репе всякий мусор типа IDE'шных файлов? У каждого встречного-поперечного своя IDE. Пусть локально настройки свои хранит

2022-10-16 21:43 UTC, Smarthard commented on migrations/2022-10-15-01-create-authors.xml
> +            </column>
Почему нельзя индексы навесить на обычную колонку авторов?

2022-10-17 07:38 UTC, BasicEC commented on .vscode/settings.json
> +}
Этот файл настраивает спелчек, вместо того, чтобы каждому возиться и настраивать его было бы удобнее хранить это в репе. Тоже самое касается, например, настроек деббагера. Вместо того, чтобы каждому приходилось возиться с его настройкой можно было бы сложить эти настройки в репу

2022-10-17 07:40 UTC, BasicEC commented on migrations/2022-10-15-01-create-authors.xml
> +            </column>
case sensitive колонка не отловит то, что `anidub` и `AniDUB` это одно и тоже. А хранить все и показывать только  в нормализованном виде - ну такое

2022-10-17 08:26 UTC, Smarthard commented on migrations/2022-10-15-01-create-authors.xml
> +            </column>
Считаю, что таблицу надо нормализировать:

1. Вешаем индекс LOWER/UPPER на колонку автора: https://stackoverflow.com/questions/3980050/how-do-i-create-an-index-in-postgresql-based-on-lowercase-only
2. Делаем регистронезависимый поиск по query типа: `SELECT id, author FROM lower(author) LIKE lower(seach_str);`

2022-10-17 09:03 UTC, Smarthard commented on migrations/2021-01-16-01-create-videos.xml
> +                                 referencedColumnNames="id"/>
не, ну миграции менять - эт сильно
давай отдельным файлом миграции это сделаем

2022-10-17 09:11 UTC, Smarthard commented on .vscode/settings.json
> +}
Спелчек - минорная штука, хранить для неё какие-то настройки в нашей репе не надо. Ещё могу понять для кодстайла. Короч, выпиливай это дело и .gitignore поправь, чтоб все файлы .vscode не коммитились. Они там сейчас разрешены только потому что файл гитигнора генерила CLI nest'а.

2022-10-17 09:13 UTC, BasicEC commented on migrations/2021-01-16-01-create-videos.xml
> +                                 referencedColumnNames="id"/>
у нас нет ниодного рабочего оркужения, легче изменить миграцию

2022-10-17 09:22 UTC, Smarthard commented on migrations/2021-01-16-01-create-videos.xml
> +                                 referencedColumnNames="id"/>
моё есть 😢

2022-10-17 09:23 UTC, Smarthard commented on migrations/2021-01-16-01-create-videos.xml
> +                                 referencedColumnNames="id"/>
ну и dev.smarthard.net ещё: https://dev.smarthard.net/api/1.0/

2022-10-17 09:24 UTC, BasicEC commented on migrations/2021-01-16-01-create-videos.xml
> +                                 referencedColumnNames="id"/>
Bruh, окееей переделаю

2022-10-22 20:21 UTC, Smarthard commented on src/routes/api/video/dto/SearchVideosRequest.dto.ts
> +export class SearchVideosRequest implements PaginationRequest, Partial<Omit<Omit<Video, 'uploader'>, 'author'>> {
```suggestion
export class SearchVideosRequest implements PaginationRequest, Partial<Omit<Video, 'uploader' | 'author'>> {
```

2022-10-22 20:27 UTC, Smarthard commented on src/services/video/video.service.ts
> +    }
Нужна транзакция, не?

2022-10-22 20:29 UTC, Smarthard commented on src/services/video/video.service.ts
> +                name: Raw((_) => `UPPER(${_}) like :author`, { author: `%${name.trim().toUpperCase()}%` }),
Насколько это устойчиво на SQL Injection?

2022-10-22 21:37 UTC, BasicEC commented on src/services/video/video.service.ts
> +                name: Raw((_) => `UPPER(${_}) like :author`, { author: `%${name.trim().toUpperCase()}%` }),
ну если передать `\'drop table authors;` то ничего не упадет (я проверял). Мы не встаиваем в sql ввод пользователя. Это делается через :author, обычно такое означает что весь пользовательский ввод будет восприниматься именно как параметр и не сломает sql

2022-10-22 21:38 UTC, BasicEC commented on src/services/video/video.service.ts
> +    }
Этот метод используется внутри транзакций, и entityManager передается сюда из транзакции => не нужно

2022-10-22 21:41 UTC, BasicEC commented on src/routes/api/video/dto/SearchVideosRequest.dto.ts
> +export class SearchVideosRequest implements PaginationRequest, Partial<Omit<Omit<Video, 'uploader'>, 'author'>> {
исправил

2022-10-24 12:11 UTC, Smarthard commented on src/routes/api/author/author.controller.ts
> +    }
почему не используем class-transformer?

2022-10-24 12:15 UTC, Smarthard commented on src/routes/api/author/dto/GetAuthorsRequest.ts
> +export class GetAuthorsRequest implements Request {
сортировка тут по имени автора нужна или мб мы всегда сортированные отдаём?

2022-10-24 12:20 UTC, Smarthard commented on src/services/author/author.service.ts
> +            order: { id: 'asc' },
почему по id, а не по name?
наверное, всё же стоит сделать параметр для разных типов сортировки

2022-10-24 12:24 UTC, Smarthard commented on src/services/author/author.service.ts
> +        if (query.name && query.name.trim().length > 0) {
а ещё лучше сразу в UPPERCASE кастовать

2022-10-24 12:24 UTC, Smarthard commented on src/services/author/author.service.ts
> +        return new GetAuthorResponse(await this.repository.find(queryOptions), limit, offset);
сервисы отдают enities у нас

2022-10-24 12:26 UTC, Smarthard commented on src/services/video/video.service.ts
> +            if (video.author && video.author.trim().toUpperCase() !== entity.author.name.toUpperCase()) {
тут тоже стоит нормализировать автора
мб для этого стоит отдельную чистую функцию завести в `utils/`?

2022-10-24 12:27 UTC, Smarthard commented on src/services/video/video.service.ts
> +                name: Raw((_) => `UPPER(${_}) like :author`, { author: `%${name.trim().toUpperCase()}%` }),
По инъекции - ОК
Не забудь применить функцию нормализации автора.

2022-10-24 12:30 UTC, Smarthard commented on test/test.environment.ts
>  export class TestEnvironment {
эт что-то неиспользованное было?

2022-10-24 20:50 UTC, Smarthard requested changes
Тэк, оказывается, тут надо что-то написать, чтобы ревью отправилось полностью.
Короч, в целом нормально. Нужно только поправить моменты с нормализацией авторов в отдельной функции из utils + там поправить момент методом сервиса, который возвращает не entity и каст в DTO через class-transformer.

А и ещё стоит подумать, нужна ли разная сортировка для авторов по id и по имени + ASC/DESC. Если нет, то тогда сортируй по name, а не по id. Нет смысла выдавать авторов в разнобой.

2022-11-05 14:35 UTC, BasicEC commented on src/routes/api/author/author.controller.ts
> +    }
Он implicit и работает не так как нужно - если в entity есть поле а в dto нет, то в респонсе все равно будет поле.

2022-11-05 14:37 UTC, BasicEC commented on src/services/author/author.service.ts
> +            order: { id: 'asc' },
исправил на сортировку по имени. Выбор сортировки сейчас считаю избыточным. Апи нужно для автодополнения ввода автора, никто не будет выбирать там сортировку.

2022-11-05 14:37 UTC, BasicEC commented on src/services/author/author.service.ts
> +        if (query.name && query.name.trim().length > 0) {
Переписал, теперь тут другой код

2022-11-05 14:37 UTC, BasicEC commented on src/services/author/author.service.ts
> +        return new GetAuthorResponse(await this.repository.find(queryOptions), limit, offset);
ок, исправил

2022-11-05 14:39 UTC, BasicEC commented on test/test.environment.ts
>  export class TestEnvironment {
vs говорит они не использовались

2022-11-05 15:19 UTC, BasicEC commented on src/services/video/video.service.ts
> +            if (video.author && video.author.trim().toUpperCase() !== entity.author.name.toUpperCase()) {
сделал

2022-11-05 15:20 UTC, BasicEC commented on src/services/author/author.service.ts
> +                name: Raw((_) => `UPPER(${_}) like :name`, { name: `%${query.name.trim().toUpperCase()}%` }),
сделал

2022-11-05 16:57 UTC, Smarthard requested changes

2022-11-05 16:57 UTC, Smarthard commented on src/routes/api/author/author.controller.ts
> +        query.offset ??= 0;
Раньше мы это делали в сервисах, что поменялось?

2022-11-05 16:57 UTC, Smarthard commented on src/routes/api/author/author.controller.ts
> +    }
всё ещё не кастишь через class-transformer

2022-11-05 16:57 UTC, Smarthard commented on src/routes/api/author/dto/GetAuthorsRequest.ts
> +    @Max(100)
можно увеличить лимит до 1000+, запрос не сложный

2022-11-05 16:57 UTC, Smarthard commented on src/services/author/author.service.ts
> +        Assert.Argument('offset', offset).greaterOrEqualTo(0);
нейминг в camelCase
и че будет, если не заассертит?

2022-11-05 16:57 UTC, Smarthard commented on src/utils/postgres.utils.ts
> +    return value?.trim()?.toUpperCase();
```suggestion
    return (value || '').trim().toUpperCase();
```

2022-11-05 16:57 UTC, Smarthard commented on src/services/video/video.service.ts
> +            if (video.author && normalizeString(video.author) !== normalizeString(entity.author.name)) {
чет сложно, лучше так

```suggestion
            if (normalizeString(video.author) !== normalizeString(entity.author.name)) {
```

2022-11-05 16:57 UTC, Smarthard commented on src/services/author/author.service.ts
> +        Assert.Argument('offset', offset).greaterOrEqualTo(0);
а, ну я понял, будет вызвана серверная ошибка
короч, главное, чтоб они обрабатывались нормально

2022-11-05 17:26 UTC, BasicEC commented on src/routes/api/author/author.controller.ts
> +        query.offset ??= 0;
контракт поменялся. Раньше у меня сервис принимал request и возвращал response. А сейчас он принимает отдельные параметры и возвращает entity.

То есть сервис отвязан от контроллера. Этот контроллер решил что дефолтные значениея такие, другой решит что дефолтные другие.

2022-11-05 17:27 UTC, BasicEC commented on src/routes/api/author/author.controller.ts
> +    }
Я не понимаю, что ты от меня хочешь

2022-11-05 17:30 UTC, BasicEC commented on src/services/author/author.service.ts
> +        Assert.Argument('offset', offset).greaterOrEqualTo(0);
Это защита от дурака. Ошибки не должны кидаться, а если кидаются значит кто-то неправильно использует сервис

2022-11-05 17:32 UTC, BasicEC commented on src/utils/postgres.utils.ts
> +    return value?.trim()?.toUpperCase();
А зачем возвращать пустую строку если у нас null?

2022-11-05 18:34 UTC, Smarthard approved these changes

2022-11-05 18:34 UTC, merged