[#86] Convert entity to dto manually
Palus-Somni-Team/shikicinema-server pull request #88
Opened 2023-01-06 08:59 UTC by BasicEC

2023-01-06 09:25 UTC, BasicEC commented
@Smarthard Я заметил что у нас чет для /admin/users апихи практически нет e2e тестов. Завел задачу на эту тему: https://github.com/Palus-Somni-Team/shikicinema-server/issues/89

2023-01-08 14:15 UTC, Smarthard requested changes

2023-01-08 14:15 UTC, Smarthard commented on src/routes/api/admin/user/dto/AdminUserInfo.dto.ts
> +    public static create(user: UserEntity): AdminUserInfo {
```suggestion
    public static toDto(user: UserEntity): AdminUserInfo {
```

2023-01-08 14:15 UTC, Smarthard commented on src/routes/api/author/dto/Author.dto.ts
> +    public static create(author: AuthorEntity): Author {
```suggestion
    public static toDto(author: AuthorEntity): Author {
```

2023-01-08 14:15 UTC, Smarthard commented on src/routes/api/user/dto/UserInfo.dto.ts
> +    public static create(entity: UserEntity): UserInfo {
```suggestion
    public static toDto(entity: UserEntity): UserInfo {
```

2023-01-08 14:15 UTC, Smarthard commented on src/routes/api/video/dto/VideoResponse.dto.ts
> +    public static create(entity: VideoEntity): VideoResponse {
```suggestion
    public static toDto(entity: VideoEntity): VideoResponse {
```

2023-01-08 14:15 UTC, Smarthard commented on src/routes/auth/dto/OwnerUserInfo.dto.ts
> +    public static create(entity: UserEntity): OwnerUserInfo {
```suggestion
    public static toDto(entity: UserEntity): OwnerUserInfo {
```

2023-01-08 14:15 UTC, Smarthard commented on src/routes/auth/dto/UploadTokenInfo.dto.ts
> +    public static create(entity: UploadTokenEntity): UploadTokenInfo {
```suggestion
    public static toDto(entity: UploadTokenEntity): UploadTokenInfo {
```

2023-01-08 14:15 UTC, Smarthard commented on src/routes/auth/dto/UploaderInfo.dto.ts
> +    public static create(entity: UploaderEntity): UploaderInfo {
```suggestion
    public static toDto(entity: UploaderEntity): UploaderInfo {
```

2023-01-08 14:15 UTC, Smarthard commented on src/utils/class-transform.utils.ts
> +        transform(target, key);
это же покрыто тестами у нас?

2023-01-08 14:18 UTC, BasicEC commented on src/utils/class-transform.utils.ts
> +        transform(target, key);
У меня была идея вообще выпилить эту функцию, но все сломалось. Так что видимо покрыто

2023-01-08 14:21 UTC, BasicEC commented on src/routes/api/admin/user/dto/AdminUserInfo.dto.ts
> +    public static create(user: UserEntity): AdminUserInfo {
Чем тебя имя метода не устроило? Может так вмерджим?)

2023-01-08 14:23 UTC, BasicEC commented on src/routes/api/admin/user/dto/AdminUserInfo.dto.ts
> +    public static create(user: UserEntity): AdminUserInfo {
Почему не fromEntity тогда уж?) toDto я бы назвал метод если бы он жил в entity. Но вообще кажется и так понятно что происходит

2023-01-08 18:30 UTC, Smarthard commented on src/routes/api/admin/user/dto/AdminUserInfo.dto.ts
> +    public static create(user: UserEntity): AdminUserInfo {
решили заменить на конструкторы

2023-01-08 20:51 UTC, BasicEC commented
@Smarthard посмотрел твой коммит - норм, можем мерджить. PR мой и поставить аппрув я не могу - это на тебе.

2023-01-09 06:57 UTC, Smarthard approved these changes

2023-01-09 06:58 UTC, merged