#78 Implement OAuth Code Flow
Palus-Somni-Team/shikicinema-server pull request #95
Opened 2023-02-01 19:19 UTC by Smarthard

2023-03-18 11:10 UTC, BasicEC requested changes

2023-03-18 11:10 UTC, BasicEC commented on src/routes/oauth/oauth-with-authorization.controller.ts
> +@UseGuards(AuthenticatedGuard, BanStatusGuard(BanStatusEnum.DISALLOW_BANNED))
Мне не нравиться BanStatusEnum. Если ты хочешь сделать фичу опциональной, то нужно
1. Сделать возможность отключать эту фичу из конфига и сразу во всех контроллерах в которых она будет использоваться (а то придется над каждым контроллером это исправлять)
2. В случае если  `BanStatusEnum.DISALLOW_BANNED` Guard вообще не должен работать. А то мы пользователя нашли, на роли его посмотрели, а потом оказалось, что `с.DISALLOW_BANNED` и все напрасно
3. И было бы клево тесты добавить на то, что отключение этой фичи работает.

Я бы в этом PR сделал фичу обязательной и убил `BanStatusEnum.DISALLOW_BANNED`, а на то чтобы сделать фичу опциональной можно завести отдельный тикет. Это не musthave в этом PR и для прода

2023-03-18 11:10 UTC, BasicEC commented on test/test.client.ts
> +    }
Методы которые делают запрос и не делают `checkResponse` нужно называть с окончанием Raw. 

`refreshToken` -> `refreshTokenRaw`
`getCallback` -> `getCallbackRaw`
`getAccessToken` -> `getAccessTokenRaw`

2023-03-18 11:10 UTC, BasicEC commented on test/spec/oauth.e2e.spec.ts
> +            `should return 403 for unauthorized GET /oauth/${provider}`,
Если пользовать unauthorized, то логичнее вернуть 401, не?

2023-03-22 15:28 UTC, Smarthard commented on src/routes/oauth/oauth-with-authorization.controller.ts
> +@UseGuards(AuthenticatedGuard, BanStatusGuard(BanStatusEnum.DISALLOW_BANNED))
- BanStatusEnum выпилен
- guard для забаненных пользователей теперь только запрещает забаненному пользователю доступ

2023-03-22 15:29 UTC, Smarthard commented on test/spec/oauth.e2e.spec.ts
> +            `should return 403 for unauthorized GET /oauth/${provider}`,
Теперь 401 для всех неавторизованных пользователей (AuthenticatedGuard)

2023-03-22 15:57 UTC, BasicEC approved these changes

2023-03-22 16:31 UTC, merged